# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLmJc0_6v3EsbVYKQVe2fyoWiT6tG3ZK
"""

s="hello world i am shifa"
c=v=0
vowels="AEIOUaeiou"
for ch in s:
  if ch.isalpha():
    if ch in vowels:
      v+=1
    else:
      c+=1
print("vowels=",v)
print("consonants=",c)

s="shifakhan"
palin=s[::-1]
if(s==palin):
  print("palindrone")
else:
  print("not palindrone")

